version: "4"
services:
  postgres:
    image: library/postgres:14
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  registration-service:
    build: ./registration_service
    #image: xelagurd/rsoi-lab2_registration-service:latest
    container_name: registration-service
    ports:
      - "8761:8761"
    depends_on:
      - postgres

  gateway-service:
    build: ./gateway_service
    #image: xelagurd/rsoi-lab2_gateway-service:latest
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  session-service:
    build: ./session_service
    container_name: session-service
    ports:
      - "8010:8010"
    depends_on:
      - postgres

  scooter-service:
    build: ./scooter_service
    #image: xelagurd/rsoi-lab2_scooter-service:latest
    container_name: scooter-service
    ports:
      - "8020:8020"
    depends_on:
      - postgres

  station-service:
    build: ./station_service
    container_name: station-service
    ports:
      - "8030:8030"
    depends_on:
      - postgres

  rental-service:
    build: ./rental_service
    #image: xelagurd/rsoi-lab2_rental-service:latest
    container_name: rental-service
    ports:
      - "8040:8040"
    depends_on:
      - postgres

  payment-service:
    build: ./payment_service
    #image: xelagurd/rsoi-lab2_payment-service:latest
    container_name: payment-service
    ports:
      - "8050:8050"
    depends_on:
      - postgres

  statistic-service:
    build: ./statistic_service
    container_name: statistic-service
    ports:
      - "8060:8060"
    depends_on:
      - postgres

volumes:
  db-data: